# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linter Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: rbob86/lookml-linter@ericfixessomestuff
        with:
          lookMlProject: ./
          configFile: ${{ github.workspace }}/config.example.yaml
#     - run: |
#         echo "This is the workspace"
#         pwd
#         python -m linter.main config.example.yaml
        

